server:
  port: 8080
  servlet.context-path: /
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sample
    username: root
    password: 123456@A
  jpa:
    show-sql: true

springdoc:
  swagger-ui:
    enabled: true
    path: /docs
  api-docs:
    enabled: true